list(APPEND COMPILE_DEFINITIONS "NAPI_VERSION=8")
list(APPEND COMPILE_DEFINITIONS "NAPI_CPP_EXCEPTIONS")
list(APPEND COMPILE_DEFINITIONS "HOST_BINARY=\"${NODE_HOST_BINARY}\"")

list(APPEND INCLUDE_DIRECTORIES "${NODE_DEV_DIR}/include")
list(APPEND INCLUDE_DIRECTORIES "${NODE_DEV_DIR}/include/node")
list(APPEND INCLUDE_DIRECTORIES "${NODE_ADDON_DEV_DIR}")

list(APPEND LINK_LIBRARIES "${NODE_DEV_DIR}/lib/${OS_XARCH}/node.lib")
list(APPEND LINK_LIBRARIES "delayimp.lib")

add_library(node-addon-api INTERFACE IMPORTED)
set_target_properties(node-addon-api PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "${COMPILE_DEFINITIONS}"
    INTERFACE_INCLUDE_DIRECTORIES "${INCLUDE_DIRECTORIES}"
    INTERFACE_LINK_LIBRARIES "${LINK_LIBRARIES}"
    INTERFACE_LINK_OPTIONS "/DELAYLOAD:${NODE_HOST_BINARY}"
    INTERFACE_SOURCES "${NODE_DEV_DIR}/src/win_delay_load_hook.cc")

function(configure_node_module target)
    target_link_libraries(${target} PRIVATE node-addon-api)
    set_target_properties(${target} PROPERTIES
        SUFFIX "-${OS_PLATFORM}-${OS_ARCH}.node"
        PDB_NAME "${target}-${OS_PLATFORM}-${OS_ARCH}")
endfunction()
